import Head from "next/head";

import { Container, Row, Col, Text, Spacer } from "@nextui-org/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Levi J Mason</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Spacer />

      <main>
        <Container fluid>
          <Text h1>Does this have space? </Text>
        </Container>
      </main>
    </>
  );
}
